accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    path('', views.Dashboard.as_view(), name='dashboard'), # dashboard url

    path('register/', views.Register.as_view(), name='register'), # register new user
    path('edit/', views.EditProfile.as_view(), name='edit'), # edit Profile

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('summaries/', include('summaries.urls', namespace='summaries')),
]

# serving media files only during developement
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

summaries/urls.py
from django.urls import include, path
from . import views


app_name = 'summaries'


urlpatterns = [

    # *********************** summariy crud urls *********************** 
    path('', views.SummaryList.as_view(), name='summary_list'), # all summaries 
    path('<int:tag_id>/', views.SummaryList.as_view(), name='summary_list'), # filter summaries by tags
    path('<int:category_id>/', views.SummaryList.as_view(), name='summary_list'), # filter summaries by categories
    path('add/', views.SummaryCreate.as_view(), name='summary_add'), # add summary
    path('<int:pk>/detail/', views.SummaryDetail.as_view(), name='summary_detail'), # summary details
    path('<int:pk>/update/', views.SummaryUpdate.as_view(), name='summary_update'), # edit summary
    path('<int:pk>/delete/', views.SummaryDelete.as_view(), name='summary_delete'), # delete summary

    # *********************** download summary using weasyprint *********************** 
    path('<int:pk>/download', views.SummaryDownload.as_view(), name='summary_download'), 

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %} book summaries {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block some_css_style %} {% endblock %}
  </head>
  <body>

    <div class="container bg-light ">
      {% include 'navbar.html' %}

      <!-- display messages using django messages framework -->
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div {% if message.tags %} class="alert alert-danger" {% endif %}>{{ message }}</div>
        {% else %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}

      <br />

      {% block content %} {% endblock %}
    </div>

    <script src='{% static 'js/jquery-3.5.1.min.js' %}'></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block some_jquery_code %} {% endblock %}

  </body>
</html>

templates/navbar.html
{% load summary_filters %}

<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><i class="bi bi-book-fill"></i> Book summaries</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a href="{% url "summaries:summary_list" %}" class="nav-link">Home</a>
        </li>
        {% category_list_for_navbar %}
        <li class="nav-item">
          <a href="{% url "summaries:summary_add" %}" class="nav-link"><i class="bi bi-plus"></i> add summary</a>
        </li>
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url "login" %}" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="{% url "register" %}" class="nav-link">Register</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url "logout" %}" class="nav-link">Logout</a>
        </li>
        <li class="nav-item">
          <a href="{% url "dashboard" %}" class="nav-link">Hello <b>{{ request.user.username }}</b></a>
        </li>
        {% endif %}

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>