accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    path('', views.Dashboard.as_view(), name='dashboard'), # dashboard url

    path('register/', views.Register.as_view(), name='register'), # register new user
    path('edit/', views.EditProfile.as_view(), name='edit'), # edit Profile

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('summaries/', include('summaries.urls', namespace='summaries')),
]

# serving media files only during developement
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

summaries/urls.py
from django.urls import include, path
from . import views


app_name = 'summaries'


urlpatterns = [

    # *********************** summariy crud urls *********************** 
    path('', views.SummaryList.as_view(), name='summary_list'), # all summaries 
    path('<int:tag_id>/', views.SummaryList.as_view(), name='summary_list'), # filter summaries by tags
    path('<int:category_id>/', views.SummaryList.as_view(), name='summary_list'), # filter summaries by categories
    path('add/', views.SummaryCreate.as_view(), name='summary_add'), # add summary
    path('<int:pk>/detail/', views.SummaryDetail.as_view(), name='summary_detail'), # summary details
    path('<int:pk>/update/', views.SummaryUpdate.as_view(), name='summary_update'), # edit summary
    path('<int:pk>/delete/', views.SummaryDelete.as_view(), name='summary_delete'), # delete summary

    # *********************** download summary using weasyprint *********************** 
    path('<int:pk>/download', views.SummaryDownload.as_view(), name='summary_download'), 

]

summaries/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from taggit.managers import TaggableManager



class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now =True)

    class Meta:
        abstract = True
        ordering = ('created', )


class Category(TimeStampedModel):
    name = models.CharField(max_length=100)
                     
    def __str__(self):
        return self.name
                     

class Summary(TimeStampedModel):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='summaries')
    body = models.TextField(blank=True)
    tags = TaggableManager()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='summaries')

    def get_absolute_url(self):
        return reverse('summaries:summary_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title
                     

summaries/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.core.files.storage import FileSystemStorage
import datetime
# messages framework
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
# class-based generic views
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
# third party imports
from taggit.models import Tag
from weasyprint import HTML
# import models
from django.contrib.auth.models import User
from .models import Summary



# display summary list
class SummaryList(ListView): 
    model = Summary
    template_name = 'summaries/summary/summary_list.html'
    context_object_name = 'summary_list'
    paginate_by = 5

    def get_queryset(self):
        # filter summary list by tags
        if 'tag_id' in self.kwargs:
            tag = get_object_or_404(Tag, pk=self.kwargs['tag_id']) # get the tag instance
            summary_list =  super().get_queryset().filter(tags__in=[tag]) # filter summary list
            return summary_list
        # filter summary list by category
        elif 'category_id' in self.kwargs:
            category = get_object_or_404(Category, pk=self.kwargs['category_id']) # get the category instance
            summary_list =  super().get_queryset().filter(category=category) # filter summary list
            return summary_list
        else:
            return super().get_queryset()


# display summary details
class SummaryDetail(DetailView):
    model = Summary
    template_name = 'summaries/summary/summary_detail.html'
    context_object_name = 'summary'


# create summary 
class SummaryCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView): 
    model = Summary
    template_name = 'summaries/summary/summary_form_create.html' 
    fields = ['title', 'category', 'body', 'tags']
    success_message = "your summary has been added successfully"

    def form_valid(self, form):
        form.instance.author = self.request.user # add summary author 
        return super().form_valid(form)


# edit summary 
class SummaryUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Summary
    template_name = 'summaries/summary/summary_form_update.html' 
    fields = ['title', 'category', 'body', 'tags']
    success_message = "your summary has been edited successfully"


    def form_valid(self, form):
        # user should be the summary author 
        if form.instance.author == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse('you are not summary author')


# delete summary 
class SummaryDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Summary
    template_name = 'summaries/summary/summary_confirm_delete.html' 
    success_message = "your summary has been deleted"
    success_url = reverse_lazy('summaries:summary_list')

    def form_valid(self, form):
        # user should be the summary owner 
        if form.instance.author == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse('you are not summary owner')

    def delete(self, request, *args, **kwargs):
        messages.error(request, self.success_message)
        return super().delete(request, *args, **kwargs)


# download summary with weasyprint
class SummaryDownload(View):

    def get(self, request, *args, **kwargs):
        summary = get_object_or_404(Summary, pk=kwargs['pk'])
        context = {'summary': summary, 'date': datetime.datetime.now()}
        html_string = render_to_string('summaries/summary/summary_as_pdf.html', context, request=request)

        html = HTML(string=html_string)
        html.write_pdf(target='/tmp/mypdf.pdf');

        fs = FileSystemStorage('/tmp')
        with fs.open('mypdf.pdf') as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = 'inline; filename="mypdf.pdf"'
            return response

summaries/templates/summaries/summary/category_list.html
<!-- Display all tags -->
<div class="mt-5">
{% if category_list %}
    <p><b>Categories: </b>
        {% for category in category_list %}
            <a href="{% url 'summaries:summary_list' category_id=category.id %}" class="btn btn-outline-secondary btn-sm my-2">{{ category.name }}</a>
        {% endfor %}
    </p>
{% endif %}
</div>

<!-- Some styles to make those links in the middle -->
<style>
</style>

summaries/templates/summaries/summary/category_list_for_navbar.html
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    categories
  </a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    {% for category in category_list %}
    <li><a class="dropdown-item" href="{% url 'summaries:summary_list' category_id=category.id %}">{{category.name}}</a></li>
    {% endfor %}
  </ul>
</li>

summaries/templates/summaries/summary/pagination.html
<br>
<div>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link bg-success text-white">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link bg-success text-white">Previous</span>
      </li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item bg-dark">
        <span class="page-link bg-success text-white">
          {{ i }}
          <span class="sr-only">(current)</span>
        </span>
      </li>
      {% else %}
      <li class="page-item">
        <a href="?page={{ i }}" class="page-link bg-success text-white">{{ i }}</a>
      </li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link bg-success text-white">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link bg-success text-white">Next</span>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>

<!--
  <br>
  <div>
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li class="page-item">
  <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
  </li>
  {% else %}
  <li class="page-item disabled">
  <span class="page-link">Previous</span>
  </li>
  {% endif %}
  {% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="page-item active">
  <span class="page-link">
  {{ i }}
  <span class="sr-only">(current)</span>
  </span>
  </li>
  {% else %}
  <li class="page-item">
  <a href="?page={{ i }}" class="page-link">{{ i }}</a>
  </li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <li class="page-item">
  <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
  </li>
  {% else %}
  <li class="page-item disabled">
  <span class="page-link">Next</span>
  </li>
  {% endif %}
  </ul>
  </nav>
  </div>

-->

summaries/templates/summaries/summary/summary_as_pdf.html
{% load summary_filters %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      #pdf-document {
        background-color: #FBFCFC;
      }
      .header-image {
        margin: auto;
        margin: auto;
      }
    </style>

  </head>
  <body id="pdf-document">

    <div>

      <!-- Display summary.title and summary.author.username -->
      <h1>{{ summary.title }} By {{ summary.author.username }} </h1>

      <!-- Display summary body -->
      <p> {{ summary.body|markdown_format }} </p> 

      <!-- add some information about the document downloaded -->
      <div class='text-center'>
        <p> ------------------------------------------------------------------------------------------------------ </p>
        {% if user.is_authenticated %}
        <p> This summary was downloaded by <b>{{ user.username }}</b>, in {{ date }} </p>
        {% else %}
        <p> This summary was downloaded in {{ date }} </p>
        {% endif %}
        <p> ------------------------------------------------------------------------------------------------------ </p>
      </div>


    </div>

  </body>
</html>

summaries/templates/summaries/summary/summary_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type='submit' class='btn btn-danger mt-3'><i class="bi bi-trash"></i> Delete</button>
</form>


{% endblock %}

summaries/templates/summaries/summary/summary_detail.html
{% extends 'base.html' %}
{% load summary_filters %}

{% block content %}


<!-- Display summary.title and summary.author.username -->
<h2>{{ summary.title }} By {{ summary.author.username }} </h2>

<!-- Display summary body -->
<p> {{ summary.body|markdown_format }} </p> 

<!-- link to download summary -->
<a href="{% url 'summaries:summary_download' pk=summary.pk %}"  target="_blank" class='btn btn-dark mt-3 mb-3'><i class="bi bi-download"></i> Download this summary</a>


<!-- Display 'Edit' and 'Delete' buttons -->
{% if user.is_authenticated and summary.author == request.user %}
<p>
<a href="{% url 'summaries:summary_update' summary.pk %}" class='btn btn-dark mt-3 mb-5'><i class="bi bi-pencil"></i> Edit</a>
<a href="{% url 'summaries:summary_delete' summary.pk %}" class='btn btn-danger mt-3 mb-5'><i class="bi bi-trash"></i> Delete</a>
</p>
<hr />
{% endif %}

{% endblock %}

summaries/templates/summaries/summary/summary_form_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}


<h3 class='text-center'>Add New Summary</h3>

<form action="{% url 'summaries:summary_add' %}" method="post" novalidate enctype="multipart/form-data" class="uniForm">

  <!-- rendering form fields manualy and using django-widget-tweaks to add some css classes-->
  {% for field in form %}
  <div class="form-group mb-3">

    {% if field.errors %}
      <b>{{ field.label_tag }}</b>
      {% render_field field class+="form-control is-invalid"%}
      {% for error in field.errors %}
        <div><span class="text-danger">{{ error }}</span></div>
      {% endfor %}

      {% else %}
        <b>{{ field.label_tag }}</b>
        {% render_field field class+="form-control"%}
    {% endif %}

    {% if field.help_text %}
      <p class="help">{{ field.help_text|safe }}</p>
    {% endif %}
  </div>
  {% endfor %}

  <!-- rendering form and using crispy-forms to add some css classes-->
  {% comment %} {{ form|crispy }} {% endcomment %}
  {% csrf_token %}
  <button type='submit' class='btn btn-success mt-3'><i class="bi bi-plus-lg"></i> add summary</button>
</form>

{% endblock %}

summaries/templates/summaries/summary/summary_form_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}


<h3 class='text-center'>Edit Summary</h3>

<form action="{% url 'summaries:summary_update' summary.id %}" method="post" novalidate enctype="multipart/form-data" class="uniForm">

  <!-- rendering form fields manualy and using django-widget-tweaks to add some css classes-->
  {% for field in form %}
  <div class="form-group mb-3">

    {% if field.errors %}
      <b>{{ field.label_tag }}</b>
      {% render_field field class+="form-control is-invalid" %}
      {% for error in field.errors %}
        <div><span class="text-danger">{{ error }}</span></div>
      {% endfor %}

      {% else %}
        <b>{{ field.label_tag }}</b>
        {% render_field field class+="form-control"%}
    {% endif %}

    {% if field.help_text %}
      <p class="help">{{ field.help_text|safe }}</p>
    {% endif %}
  </div>
  {% endfor %}

  <!-- rendering form and using crispy-forms to add some css classes-->
  {% comment %} {{ form|crispy }} {% endcomment %}
  {% csrf_token %}
  <button type='submit' class='btn btn-dark mt-3'><i class="bi bi-pencil"></i> Edit</button>
</form>

{% endblock %}

summaries/templates/summaries/summary/summary_list.html
{% extends 'base.html' %}
{% load summary_filters %}

{% block content %}

<div class="row">
  <h1 class='text-center'>Read Our Book Summaries</h1>

  <div class="col-md-8">

    {% if user.is_authenticated %}
    <a href="{% url 'summaries:summary_add' %}" class='btn btn-success mt-3 mb-5'><i class="bi bi-plus-lg"></i> add summary</a>
    {% endif %}

    <!-- Display list of all summaries -->
    {% for summary in summary_list %}
    <div class="card bg-light mb-3" style="max-width: 100%;">
      <div class="card-header">{{ summary.title }}</div>
      <div class="card-body">
        <!-- Link to display summarys for specific user -->
        <h4 class="card-title">Created By {{ summary.author.username }} </h4>
        <p class="card-text"> {{ summary.body|markdown_format|truncatewords_html:30 }} </p>
        <a href="{{ summary.get_absolute_url }}" class='btn btn-success'><i class="bi bi-eye"></i> Detail</a>
      </div>
    </div>
    {% empty %}
    <p>No summary yet</p>
    {% endfor %}


  </div>
  <div class="col-md-4">
    <!-- Inclusion tag that display all tags - 'blog/post/tags_list.html' -->
    {% tags_list %}
    {% category_list %}
  </div>
</div>

<!-- Display pagination only if page_obj have some value -->
{% if page_obj %}
{% include "summaries/summary/pagination.html" with page=page_obj %}
{% endif %}

{% endblock %}

summaries/templates/summaries/summary/tags_list.html
<!-- Display all tags -->
<div class="mt-5">
{% if tags_list %}
    <p><b>Tags: </b>
        {% for tag in tags_list %}
            <a href="{% url 'summaries:summary_list' tag_id=tag.id %}" class="btn btn-outline-secondary btn-sm my-2">{{ tag.name }}</a>
        {% endfor %}
    </p>
{% endif %}
</div>